ONE
ONE FIVE SIX TWO FIVE
FOUR OH OH OH OH OH OH
FIVE OH OH OH OH OH OH
THREE ONE FOUR ONE FIVE NINER TWO
THREE ONE FOUR ONE FIVE NINER THREE
SEVEN SIX EIGHT OH THREE THREE
ZERO
FOUR TWO NINE FOUR NINE SIX SEVEN TWO NINE FIVE
FOUR THREE OH ONE FOUR OH NINE
FOUR THREE OH ONE FOUR ONE OH





