    	PLEASE NOTE THIS PROGRAM TESTS COMPUTED COME FROM
	DO .2 <- #2
(1)    	DO .1 <- #1
(3)	DO READ OUT #5
	DO COME FROM .1
(256)	DO READ OUT #2
	DO .2 <- '.2$#0'~#43691
(5)	DO READ OUT #3
	DO READ OUT #4
	DO .1 <- #5
	PLEASE DO (3) NEXT
	PLEASE COME FROM .2
	DO WRITE IN .1
	DO WRITE IN .2
(999)	DO NOTHING
	PLEASE GIVE UP
