(1)	DO NOTHING
	PLEASE COME FROM (13) ONCE
	PLEASE COME FROM #11 ONCE
	DO COME FROM (1)
	DO READ OUT #1 ONCE
(6)	DO READ OUT #2 AGAIN
	DO READ OUT #3
	DO ABSTAIN FROM (6) ONCE
	DON'T READ OUT #4 ONCE
(10)	DON'T READ OUT #5 AGAIN
(11)   	DO REINSTATE (10) ONCE
	DO READ OUT #6
(13)	DON'T READ OUT #7
	DO REINSTATE (17)
(15)   	DO (19) NEXT ONCE
(16)   	PLEASE READ OUT #8
(17)	DON'T (15) NEXT AGAIN
	PLEASE GIVE UP
(19)	PLEASE READ OUT #9
	DO (16) NEXT
	
