       PLEASE DO (1) NEXT
       DO ERROR: NEXTING NOT WORKING
       DO SECTION A: CONTROL FLOW
(1)    DO FORGET #1
       DO .1 <- #2
       PLEASE DO (2) NEXT
       DO (11) NEXT
       DO ERROR: IGNORING NOT WORKING
(7)    DO FORGET #2
       DO REMEMBER .1
       DO .1 <- #2
       DO (12) NEXT
       DO ABSTAIN FROM (50)
(50)   PLEASE DO (51) NEXT
       DO ABSTAIN FROM (52)
       DO REINSTATE (52)
(52)   PLEASE DO (123) NEXT
       DO ERROR: LABEL REINSTATING NOT WORKING
(123)  PLEASE DO FORGET #1
       DO .1 <- #2
       DO STASH .1
       DO .1 <- #1
       DO RETRIEVE .1
       PLEASE DO (125) NEXT
       PLEASE DO (124) NEXT
(125)  PLEASE DO (126) NEXT
       DO ERROR: RETRIEVING OR STASHING NOT WORKING
(126)  DO RESUME .1
       DO ERROR
(12)   PLEASE DO (13) NEXT
       DO ERROR: REMEMBERING NOT WORKING
(13)   DO RESUME .1
       DO ERROR
(11)   PLEASE DO (111) NEXT
       DO (7) NEXT
(111)  DO .1 <- #1
       DO IGNORE .1
       DO .1 <- #2
       DO RESUME .1
(2)    DO (5) NEXT
       DO ERROR
(5)    DO RESUME .1
       DO ERROR: RESUMING NOT WORKING
(51)   DO ERROR: LABEL ABSTENTION NOT WORKING
       DO SECTION B: CALCULATION
(124)  PLEASE FORGET #1
       DO .1 <- #3
       DO .1 <- .&1
       PLEASE DO (501) NEXT
       DO ERROR IN & OPERATION
(501)  PLEASE DO (502) NEXT
       DO ERROR IN & OPERATION
(502)  PLEASE DO (603) NEXT
       DO FORGET #2
       DO .1 <- #2
       DO .1 <- .V1
       PLEASE DO (601) NEXT
       DO .2 <- #32773
       DO .2 <- .?2
       DO .2 <- .&2
       PLEASE DO (701) NEXT
       DO .1 <- #7~#5
       PLEASE DO (901) NEXT
       DO .1 <- #1$#0
       DO (950) NEXT
       DO THIS TEST HAS BEEN SUCCESSFULLY COMPLETED
(950)  PLEASE DO (951) NEXT   
       DO ERROR IN $'ING
(951)  DO RESUME .1
(901)  PLEASE DO (902) NEXT
       DO ~ ERROR
(902)  PLEASE DO (903) NEXT
       DO ~ ERROR
(903)  DO RESUME .1
(701)  PLEASE DO (702) NEXT
       DO ERROR IN ? XOR OPERATION
(702)  PLEASE DO (603) NEXT
       DO ERROR IN ? XOR OPERATION
(601)  PLEASE DO (602) NEXT
       DO ERROR IN V OPERATION
(602)  PLEASE DO (603) NEXT
       DO ERROR IN V OPERATION
(603)  DO RESUME .1
